import type { Terminology } from './transform';

export const defaultTerminology = {
  phrases: [
    ['GitHub Actions', 'Liturgies'],
    ['pull requests', 'rites of integration'],
    ['Pull requests', 'Rites of Integration'],
    ['Pull Requests', 'Rites of Integration'],
    ['pull request', 'rite of integration'],
    ['Pull request', 'Rite of Integration'],
    ['Pull Request', 'Rite of Integration'],
    ['review required', 'inquisitorial approval required'],
    ['Review required', 'Inquisitorial approval required'],
    ['Review Required', 'Inquisitorial Approval Required'],
    ['security scan failed', 'the Inquisition detected traces of Chaos corruption'],
    ['Security scan failed', 'The Inquisition detected traces of Chaos corruption'],
    ['unsigned artifact', 'relic without a Purity Seal'],
    ['Unsigned artifact', 'Relic without a Purity Seal'],
    ['waiting for checks', "awaiting the Omnissiah's blessing"],
    ['Waiting for checks', "Awaiting the Omnissiah's blessing"],
    ['checks passed', 'purity trials blessed'],
    ['Checks passed', 'Purity Trials Blessed'],
    ['checks failed', 'purity trials tainted'],
    ['Checks failed', 'Purity Trials Tainted'],
  ],
  words: [
    ['repositories', 'reliquaries'],
    ['Repositories', 'Reliquaries'],
    ['repository', 'reliquary'],
    ['Repository', 'Reliquary'],
    ['commits', 'inscriptions'],
    ['Commits', 'Inscriptions'],
    ['commit', 'inscription'],
    ['Commit', 'Inscription'],
    ['branches', 'crusade paths'],
    ['Branches', 'Crusade Paths'],
    ['branch', 'crusade path'],
    ['Branch', 'Crusade Path'],
    ['merge', 'consecrate'],
    ['Merge', 'Consecrate'],
    ['merged', 'consecrated'],
    ['Merged', 'Consecrated'],
    ['workflow', 'ritual'],
    ['Workflow', 'Ritual'],
    ['workflows', 'rituals'],
    ['Workflows', 'Rituals'],
    ['checks', 'purity trials'],
    ['Checks', 'Purity Trials'],
    ['check', 'purity trial'],
    ['Check', 'Purity Trial'],
    ['passed', 'blessed'],
    ['Passed', 'Blessed'],
    ['failed', 'tainted'],
    ['Failed', 'Tainted'],
    ['approved', 'sanctified'],
    ['Approved', 'Sanctified'],
    ['approve', 'sanctify'],
    ['Approve', 'Sanctify'],
    ['deploy', 'dispatch to Holy Terra'],
    ['Deploy', 'Dispatch to Holy Terra'],
    ['deploys', 'dispatches to Holy Terra'],
    ['Deploys', 'Dispatches to Holy Terra'],
    ['deploying', 'appeasing the Machine Spirit'],
    ['Deploying', 'Appeasing the Machine Spirit'],
    ['deployment', 'holy dispatch'],
    ['Deployment', 'Holy Dispatch'],
    ['release', 'sacred release'],
    ['Release', 'Sacred Release'],
    ['releases', 'sacred releases'],
    ['Releases', 'Sacred Releases'],
    ['artifact', 'sacred relic'],
    ['Artifact', 'Sacred Relic'],
    ['artifacts', 'sacred relics'],
    ['Artifacts', 'Sacred Relics'],
    ['loading', 'reciting the Litany of Compilation'],
    ['Loading', 'Reciting the Litany of Compilation'],
  ],
} as const satisfies Terminology;
