import type { Terminology } from './transform';

export const defaultTerminology = {
  phrases: [
    ['GitHub Actions', 'Liturgies'],
    ['Security and quality', 'Purity and Integrity'],
    ['security and quality', 'purity and integrity'],
    ['Latest commit', 'Latest Inscription'],
    ['latest commit', 'latest inscription'],
    ['Last commit message', 'Last inscription message'],
    ['last commit message', 'last inscription message'],
    ['Last commit date', 'Last inscription date'],
    ['last commit date', 'last inscription date'],
    ['Folders and files', 'Vaults and Schematics'],
    ['folders and files', 'vaults and schematics'],
    ['Go to file', 'Locate Schematic'],
    ['go to file', 'locate schematic'],
    ['View all files', 'View all Schematics'],
    ['view all files', 'view all schematics'],
    ['Repository files navigation', 'Reliquary schematics navigation'],
    ['repository files navigation', 'reliquary schematics navigation'],
    ['Repository files', 'Reliquary Schematics'],
    ['repository files', 'reliquary schematics'],
    ['View commit history for this file', 'View inscription chronicle for this schematic'],
    ['view commit history for this file', 'view inscription chronicle for this schematic'],
    ['Saved searches', 'Recorded Auguries'],
    ['saved searches', 'recorded auguries'],
    [
      'Use saved searches to filter your results more quickly',
      'Use recorded auguries to filter your results more quickly',
    ],
    ['New issue', 'New Anomaly'],
    ['new issue', 'new anomaly'],
    ['New pull request', 'New Rite of Integration'],
    ['new pull request', 'new rite of integration'],
    ['Open Pull Request', 'Open Rite of Integration'],
    ['Open pull requests', 'Open Rites of Integration'],
    ['open pull requests', 'open rites of integration'],
    ['Draft Pull Request', 'Draft Rite of Integration'],
    ['draft pull request', 'draft rite of integration'],
    ['Files changed', 'Altered Schematics'],
    ['files changed', 'altered schematics'],
    ['Source code', 'Source Schematics'],
    ['source code', 'source schematics'],
    ['Choose a tag', 'Choose a Sigil'],
    ['choose a tag', 'choose a sigil'],
    ['Code of conduct', 'Conduct Codex'],
    ['code of conduct', 'conduct codex'],
    ['Security policy', 'Purity Protocol'],
    ['security policy', 'purity protocol'],
    ['pull requests', 'rites of integration'],
    ['Pull requests', 'Rites of Integration'],
    ['Pull Requests', 'Rites of Integration'],
    ['pull request', 'rite of integration'],
    ['Pull request', 'Rite of Integration'],
    ['Pull Request', 'Rite of Integration'],
    ['review required', 'inquisitorial approval required'],
    ['Review required', 'Inquisitorial approval required'],
    ['Review Required', 'Inquisitorial Approval Required'],
    ['security scan failed', 'the Inquisition detected traces of Chaos corruption'],
    ['Security scan failed', 'The Inquisition detected traces of Chaos corruption'],
    ['unsigned artifact', 'relic without a Purity Seal'],
    ['Unsigned artifact', 'Relic without a Purity Seal'],
    ['waiting for checks', "awaiting the Omnissiah's blessing"],
    ['Waiting for checks', "Awaiting the Omnissiah's blessing"],
    ['checks passed', 'purity trials blessed'],
    ['Checks passed', 'Purity Trials Blessed'],
    ['checks failed', 'purity trials tainted'],
    ['Checks failed', 'Purity Trials Tainted'],
    ['status checks', 'purity trials'],
    ['Status checks', 'Purity Trials'],
    ['workflow runs', 'ritual runs'],
    ['Workflow runs', 'Ritual Runs'],
    ['in progress', 'ritual in progress'],
    ['In progress', 'Ritual in Progress'],
    ['queued', 'awaiting rite'],
    ['Queued', 'Awaiting Rite'],
    ['success', 'blessed'],
    ['Success', 'Blessed'],
    ['failure', 'tainted'],
    ['Failure', 'Tainted'],
    ['cancelled', 'rite cancelled'],
    ['Cancelled', 'Rite Cancelled'],
    ['canceled', 'rite canceled'],
    ['Canceled', 'Rite Canceled'],
    ['skipped', 'rite skipped'],
    ['Skipped', 'Rite Skipped'],
    ['neutral', 'awaiting judgment'],
    ['Neutral', 'Awaiting Judgment'],
    ['timed out', 'rite timed out'],
    ['Timed out', 'Rite Timed Out'],
    ['action required', 'tech-priest action required'],
    ['Action required', 'Tech-Priest Action Required'],
    ['Run workflow', 'Begin Ritual'],
    ['run workflow', 'begin ritual'],
    ['Filter workflow runs', 'Filter ritual runs'],
    ['filter workflow runs', 'filter ritual runs'],
    ['All workflows', 'All rituals'],
    ['all workflows', 'all rituals'],
    ['Filter by Status', 'Filter by Purity State'],
    ['filter by status', 'filter by purity state'],
  ],
  words: [
    ['repositories', 'reliquaries'],
    ['Repositories', 'Reliquaries'],
    ['repository', 'reliquary'],
    ['Repository', 'Reliquary'],
    ['issues', 'anomalies'],
    ['Issues', 'Anomalies'],
    ['issue', 'anomaly'],
    ['Issue', 'Anomaly'],
    ['actions', 'liturgies'],
    ['Actions', 'Liturgies'],
    ['projects', 'endeavors'],
    ['Projects', 'Endeavors'],
    ['project', 'endeavor'],
    ['Project', 'Endeavor'],
    ['insights', 'auguries'],
    ['Insights', 'Auguries'],
    ['forks', 'divergences'],
    ['Forks', 'Divergences'],
    ['fork', 'diverge'],
    ['Fork', 'Diverge'],
    ['stars', 'benedictions'],
    ['Stars', 'Benedictions'],
    ['star', 'benediction'],
    ['Star', 'Benediction'],
    ['tags', 'sigils'],
    ['Tags', 'Sigils'],
    ['tag', 'sigil'],
    ['Tag', 'Sigil'],
    ['notifications', 'vox alerts'],
    ['Notifications', 'Vox Alerts'],
    ['notification', 'vox alert'],
    ['Notification', 'Vox Alert'],
    ['about', 'dossier'],
    ['About', 'Dossier'],
    ['history', 'chronicle'],
    ['History', 'Chronicle'],
    ['public', 'unsealed'],
    ['Public', 'Unsealed'],
    ['readme', 'canticle'],
    ['Readme', 'Canticle'],
    ['activity', 'activity log'],
    ['Activity', 'Activity Log'],
    ['languages', 'tongues'],
    ['Languages', 'Tongues'],
    ['license', 'writ of sanction'],
    ['License', 'Writ of Sanction'],
    ['topics', 'runes'],
    ['Topics', 'Runes'],
    ['contributors', 'adepts'],
    ['Contributors', 'Adepts'],
    ['contributor', 'adept'],
    ['Contributor', 'Adept'],
    ['watchers', 'watch servitors'],
    ['Watchers', 'Watch Servitors'],
    ['watcher', 'watch servitor'],
    ['Watcher', 'Watch Servitor'],
    ['assignees', 'assigned adepts'],
    ['Assignees', 'Assigned Adepts'],
    ['assignee', 'assigned adept'],
    ['Assignee', 'Assigned Adept'],
    ['authors', 'scribes'],
    ['Authors', 'Scribes'],
    ['author', 'scribe'],
    ['Author', 'Scribe'],
    ['labels', 'seals'],
    ['Labels', 'Seals'],
    ['label', 'seal'],
    ['Label', 'Seal'],
    ['milestones', 'omens'],
    ['Milestones', 'Omens'],
    ['milestone', 'omen'],
    ['Milestone', 'Omen'],
    ['reviews', 'scrutinies'],
    ['Reviews', 'Scrutinies'],
    ['review', 'scrutiny'],
    ['Review', 'Scrutiny'],
    ['conversation', 'vox log'],
    ['Conversation', 'Vox Log'],
    ['compare', 'compare rites'],
    ['Compare', 'Compare Rites'],
    ['Assets', 'Sacred Relics'],
    ['commits', 'inscriptions'],
    ['Commits', 'Inscriptions'],
    ['commit', 'inscription'],
    ['Commit', 'Inscription'],
    ['branches', 'crusade paths'],
    ['Branches', 'Crusade Paths'],
    ['branch', 'crusade path'],
    ['Branch', 'Crusade Path'],
    ['merge', 'consecrate'],
    ['Merge', 'Consecrate'],
    ['merged', 'consecrated'],
    ['Merged', 'Consecrated'],
    ['workflow', 'ritual'],
    ['Workflow', 'Ritual'],
    ['workflows', 'rituals'],
    ['Workflows', 'Rituals'],
    ['checks', 'purity trials'],
    ['Checks', 'Purity Trials'],
    ['check', 'purity trial'],
    ['Check', 'Purity Trial'],
    ['passed', 'blessed'],
    ['Passed', 'Blessed'],
    ['failed', 'tainted'],
    ['Failed', 'Tainted'],
    ['approved', 'sanctified'],
    ['Approved', 'Sanctified'],
    ['approve', 'sanctify'],
    ['Approve', 'Sanctify'],
    ['deploy', 'dispatch to Holy Terra'],
    ['Deploy', 'Dispatch to Holy Terra'],
    ['deploys', 'dispatches to Holy Terra'],
    ['Deploys', 'Dispatches to Holy Terra'],
    ['deploying', 'appeasing the Machine Spirit'],
    ['Deploying', 'Appeasing the Machine Spirit'],
    ['deployment', 'holy dispatch'],
    ['Deployment', 'Holy Dispatch'],
    ['release', 'sacred release'],
    ['Release', 'Sacred Release'],
    ['releases', 'sacred releases'],
    ['Releases', 'Sacred Releases'],
    ['artifact', 'sacred relic'],
    ['Artifact', 'Sacred Relic'],
    ['artifacts', 'sacred relics'],
    ['Artifacts', 'Sacred Relics'],
    ['loading', 'reciting the Litany of Compilation'],
    ['Loading', 'Reciting the Litany of Compilation'],
  ],
} as const satisfies Terminology;
